// Monster Types
export type MonsterType = 
  | "Effect Monster"
  | "Normal Monster"
  | "Flip Effect Monster"
  | "Link Effect Monster"
  | "Union Effect Monster"
  | "Fusion Effect Monster"
  | "Pendulum Effect Monster"
  | "Xyz Effect Monster"
  | "Synchro Effect Monster"
  | "Synchro Tuner Effect Monster"
  | "Tuner Effect Monster"
  | "Gemini Effect Monster"
  | "Fusion Tuner Monster"
  | "Tuner Normal Monster"
  | "Spirit Effect Monster"
  | "Ritual Effect Monster"
  | "Fusion Monster"
  | "Token"
  | "Fusion Pendulum Effect Monster"
  | "Link Monster"
  | "Ritual Monster"
  | "Toon Effect Monster"
  | "Pendulum Normal Monster"
  | "Synchro Pendulum Effect Monster"
  | "Ritual Tuner Effect Monster"
  | "Pendulum Tuner Effect Monster"
  | "Xyz Pendulum Effect Monster"
  | "Pendulum Flip Effect Monster"
  | "Ritual Pendulum Effect Monster"
  | "Xyz Monster"
  | "Synchro Monster"
  | "Pendulum Tuner Normal Monster"
  | "Pendulum Spirit Effect Monster"
  | "Fusion Tuner Effect Monster"
  | "Flip Tuner Effect Monster";

export type MonsterRace = 
  | "Beast"
  | "Aqua"
  | "Insect"
  | "Fish"
  | "Fiend"
  | "Spellcaster"
  | "Machine"
  | "Warrior"
  | "Beast-Warrior"
  | "Psychic"
  | "Dinosaur"
  | "Rock"
  | "Fairy"
  | "Dragon"
  | "Sea Serpent"
  | "Plant"
  | "Cyberse"
  | "Winged Beast"
  | "Wyrm"
  | "Pyro"
  | "Reptile"
  | "Zombie"
  | "Thunder"
  | "Illusion"
  | "Divine-Beast"
  | "Creator God";

export type MonsterAttribute = 
  | "DARK"
  | "LIGHT"
  | "EARTH"
  | "WATER"
  | "FIRE"
  | "WIND"
  | "DIVINE";